### PR TITLE
fix: cpfp reorg

### LINKED ISSUE #788: CPFP child transaction gets discarded if fee payer tx is also reorged
### Expected Behavior

`tx_sender` should re-send the package with the new child tx after a reorg

### Current Behavior

CPFP packages stuck in mempool because no fees

### Stps to Reproduce

1. Successfully send a CPFP tx on-chain
2. Reorg fee payer tx + CPFP package
3. Wait for fee payer tx to be on-chain again
4. Check that parent CPFP tx has no child and no fees

### Current Behavior

_No response_

### Detailed Description

CPFP packages should be saved in a temporary database until they are finalized. If a reorg is detected, it should wait until fee payer tx is on-chain and recreate CPFP package + send it.

### PR DESCRIPTION
**Pull request by atacann**
Closes #788
Fixes cpfp reorg issue that happened because a fee payer of a cpfp tx got reorged, that resulted in eviction of cpfp package in the mempool. After eviction it was never sent again by our node.

Solution I did is to just resend txs if they were not included in a block, after a new block arrives. This can fix some other issues too (some txs not getting sent by our rpc, but we never send it to rpc again if we send it successfully once)

- Adds migration support

### CODE REVIEW

File: core/src/database/tx_sender.rs [hunk 1]
```diff
@@ -583,6 +601,7 @@ impl Database {
         tx: Option<DatabaseTransaction<'_, '_>>,
         fee_rate: FeeRate,
         current_tip_height: u32,
+        latest_block_id: u32,
```
Comment (ceyhunsen) [inline core/src/database/tx_sender.rs:604]: can you document this field

File: core/src/database/tx_sender.rs [hunk 2]
```diff
@@ -647,7 +666,7 @@ impl Database {
                     -- Transaction must not be already confirmed
                     AND txs.seen_block_id IS NULL
                     -- Check if fee_rate is lower than the provided fee rate or null
-                    AND (txs.effective_fee_rate IS NULL OR txs.effective_fee_rate < $1);",
+                    AND (txs.effective_fee_rate IS NULL OR txs.effective_fee_rate < $1 OR txs.sent_block_id <> $3);",
```
Comment (ceyhunsen) [inline core/src/database/tx_sender.rs:669]: comment is outdated

File: core/src/tx_sender/mod.rs [hunk 3]
```diff
@@ -327,10 +327,11 @@ impl TxSender {
         &self,
         new_fee_rate: FeeRate,
         current_tip_height: u32,
+        latest_block_id: u32,
```
Comment (ceyhunsen) [inline core/src/tx_sender/mod.rs:330]: docs

File: core/src/tx_sender/task.rs [hunk 4]
```diff
@@ -30,6 +30,7 @@ const POLL_DELAY: Duration = if cfg!(test) {
 pub struct TxSenderTask {
     db: Database,
     current_tip_height: u32,
+    latest_block_id: Option<u32>,
```
Comment (ceyhunsen) [inline core/src/tx_sender/task.rs:33]: not sure here but can we make the dafault 0 instead of `None`? does it cause issues?

Comment (atacann) [reply core/src/tx_sender/task.rs:33]: After a restart, while txsendertask didn't process any blocks yet, it will have highest_block_id 0 and try to send all txs and set their sent_block_id on db to 0 again. I don't think this breaks anything but that's why I did it. I don't think there is an issue leaving it an option

File: core/src/database/tx_sender.rs [hunk 5]
```diff
@@ -633,12 +633,12 @@ impl Database {
     /// - Not in the cancelled list
     /// - Transaction itself is not already confirmed
     /// - Transaction and UTXO timelocks must be passed
-    /// - Fee rate is lower than the provided fee rate or null (deprecated)
+    /// - Fee rate is lower than the provided maximum fee rate (previous sends had a lower fee rate) or null (transaction wasn't sent before) OR the transaction was sent before, but the chain height increased since then, and the transaction is still not confirmed (accomplished by calling this fn with a dummy high fee rate)
```
Comment (mmtftr) [inline core/src/database/tx_sender.rs]: with u32::MAX fee rate

**Review by mmtftr — APPROVED** [review]
minor doc comments, we can merge without

**Review by mmtftr — APPROVED** [review]
