### PR TITLE
Annex support

### LINKED ISSUE #773: Add Annex support in Watchtower challenge tx proofs
A watchtower can add an annex to the Watchtower challenge tx, which currently will result in proof failing.
see: https://en.bitcoin.it/wiki/BIP_0341#:~:text=If%20an%20annex,mandatory%200x50%20prefix

### PR DESCRIPTION
**Pull request by ozankaymak**
This PR introduces taproot annex support for signature verification inside the bridge circuit.
Closes #773

### CODE REVIEW

File: circuits-lib/src/bridge_circuit/mod.rs [hunk 1]
```diff
@@ -581,13 +578,242 @@ pub fn journal_hash(
     blake3::hash(&concat_journal)
 }
 
+// Modified to panic on error
```
Comment (mmtftr) [inline circuits-lib/src/bridge_circuit/mod.rs:581]: remove modification comment

File: circuits-lib/src/bridge_circuit/mod.rs [hunk 2]
```diff
@@ -581,13 +578,242 @@ pub fn journal_hash(
...
+            .expect(expect_msg);
+        KEY_VERSION_0.consensus_encode(writer).expect(expect_msg);
+        code_separator_pos
+            .consensus_encode(writer)
+            .expect(expect_msg);
+    }
+}
+
+// Modified helper functions to be generic
+fn get_for_prevouts_generic<'a, T: Borrow<TxOut>>(
```
Comment (mmtftr) [inline circuits-lib/src/bridge_circuit/mod.rs:769]: `get_for_prevouts`

File: circuits-lib/src/bridge_circuit/mod.rs [hunk 3]
```diff
@@ -581,13 +578,242 @@ pub fn journal_hash(
...
+                Err(PrevoutsIndexError::InvalidOneIndex)
+            }
+        }
+        Prevouts::All(prevouts) => prevouts
+            .get(input_index)
+            .ok_or(PrevoutsIndexError::InvalidAllIndex),
+    }
+}
+
+fn get_all_for_prevouts_generic<'a, T: Borrow<TxOut>>(prevouts: &'a Prevouts<'a, T>) -> &'a [T] {
```
Comment (mmtftr) [inline circuits-lib/src/bridge_circuit/mod.rs:787]: `unwrap_all`

File: circuits-lib/src/bridge_circuit/mod.rs [hunk 4]
```diff
@@ -581,13 +578,242 @@ pub fn journal_hash(
...
+    match prevouts {
+        Prevouts::All(prevouts) => prevouts,
+        _ => panic!("cannot get all prevouts from a single prevout"),
+    }
+}
+
+fn check_all_generic<T: Borrow<TxOut>>(prevouts: &Prevouts<'_, T>, tx: &Transaction) {
```
Comment (mmtftr) [inline circuits-lib/src/bridge_circuit/mod.rs:794]: `check_all`
