### PR TITLE
General test additions/overhaul

### LINKED ISSUE #316: Attempt to subtract with overflow in `operator::is_profitable()`
### Expected Behavior

`operator::is_profitable()` not panicing if `input_amount` is bigger than `withdrawal_amount` and returning an error or doing modular arithmetic.

### Current Behavior

`operator::is_profitable()` panics if `input_amount` is bigger than `withdrawal_amount`.

### Stps to Reproduce

1. Start all servers with `all_servers` binary with default configuration file
2. Send `operator_new_withdrawal_sig` JSONRPC request to one of the operators

Example request: `{"jsonrpc":"2.0","id":"1","method":"operator_new_withdrawal_sig","params":{"withdrawal_idx":28,"user_sig":"53bf3ae9bdb3123b95e648b228e6d3d551799db1b4fc5ff0262456b4ff752942647d9505dd31b1a9e105a7f4449381f16ed948a17a7225b7b9477082d20707f6","input_utxo":{"outpoint":"1766e57edf7484050bc48ae3161550993761849c3b87717f9b8767c8a07d31a9:0","txout":{"script_pubkey":"5120f5c27239e760056271d945aea2dfc0e7c2f001fc56e5ebe4d29fcc11aa61ccf7","value":546}},"output_txout":{"script_pubkey":"0014d88dee095a6b14c77cff7f1787f66a08277f8f83","value":330}}}`

### Current Behavior

Modular arithmetic can be an easy fix. Or an `Err` variant can be returned.

### Detailed Description

Expected server logs are (in debug build):

```text
2024-09-24T08:30:56.191074Z TRACE jsonrpsee-http: HTTP response body: {"jsonrpc":"2.0","id":"1","method":"operator_new_withdrawal_sig","params":{"withdrawal_idx":28,"user_sig":"53bf3ae9bdb3123b95e648b228e6d3d551799db1b4fc5ff0262456b4ff752942647d9505dd31b1a9e105a7f4449381f16ed948a17a7225b7b9477082d20707f6","input_utxo":{"outpoint":"1766e57edf7484050bc48ae3161550993761849c3b87717f9b8767c8a07d31a9:0","txout":{"script_pubkey":"5120f5c27239e760056271d945aea2dfc0e7c2f001fc56e5ebe4d29fcc11aa61ccf7","value":546}},"output_txout":{"script_pubkey":"0014d88dee095a6b14c77cff7f1787f66a08277f8f83","value":330}}}
thread 'tokio-runtime-worker' panicked at /clementine/core/src/operator.rs:346:12:
attempt to subtract with overflow
```

In release builds, there is no check.

### PR DESCRIPTION
**Pull request by ceyhunsen**
# Description

This PR adds new tests and overhauls existing ones. Also adds documentation to some places.

## Notable Changes

- Integer overflow in `is_profitable` fixed (closes #316 )
- Some of the `tracing::instrument`s are removed because they have no meaning
- Some RPC functions are renamed and the rest will also be modified later (#313 )

### CODE REVIEW

File: core/src/operator.rs [hunk 1]
```diff
@@ -329,49 +329,66 @@ where
...
+    /// - `user_sig`: User's signature that is going to be used for signing withdrawal transaction input
+    /// - `input_utxo`:
+    /// - `output_txout`:
+    ///
+    /// # Returns
+    ///
+    /// Withdrawal transaction's transaction id.
     #[tracing::instrument(skip(self), err(level = tracing::Level::ERROR), ret(level = tracing::Level::TRACE))]
-    async fn new_withdrawal_sig(
+    async fn new_signed_withdrawal(
```
Comment (ekrembal) [inline core/src/operator.rs:369]: lets not change the name

File: core/src/operator.rs [hunk 2]
```diff
@@ -329,49 +329,66 @@ where
...
         }
+
+        // Calculate net profit after the withdrawal.
+        let net_profit = self.config.bridge_amount_sats - withdrawal_amount;
+
+        // Net profit must be bigger than withdrawal fee.
+        net_profit > self.config.operator_withdrawal_fee_sats.unwrap()
     }
 
+    /// Creates a withdrawal transaction with given signature and sends it to
```
Comment (ekrembal) [inline core/src/operator.rs:355]: Verifies that the withdrawal has been made on Citrea, verifies a given SIGHASH_SINGLE|ANYONECANPAY signature, checks if it is profitable and funds the withdrawal

File: core/src/operator.rs [hunk 3]
```diff
@@ -456,29 +478,31 @@ where
...
                 ));
             }
 
-            // calculate move_txid
-
+            // Calculate move_txid.
             let move_tx_handler = transaction_builder::create_move_tx(
                 deposit_outpoint,
-                &EVMAddress([0u8; 20]),
+                &EVMAddress([0u8; 20]), // TODO: This doesn't look OK.
```
Comment (ekrembal) [inline core/src/operator.rs:505]: This is ok, this is only for calculating the move_txid, that EVMaddress is written to the witness so does not effect the txid. Maybe we should note this here.

Comment (ekrembal) [reply core/src/operator.rs:505]: Or have a different function to calculte just the txid, since we use this several times

File: core/src/operator.rs [hunk 4]
```diff
@@ -491,16 +515,17 @@ where
...
+            // See: https://gist.github.com/okkothejawa/a9379b02a16dada07a2b85cbbd3c1e80
             let params = rpc_params![json!({
                 "to": "0x3100000000000000000000000000000000000002",
-                "data": format!("0x11e53a01{}", hex::encode(move_txid_bytes)), // See: https://gist.github.com/okkothejawa/a9379b02a16dada07a2b85cbbd3c1e80
+                "data": format!("0x11e53a01{}",
+                hex::encode(move_txid_bytes)),
             })];
-            let response: String = citrea_client.request("eth_call", params).await?;
-            tracing::debug!("Response from citrea: {:?}", response);
+            let response: String = citrea_client.request("eth_call", params.clone()).await?;
```
Comment (ekrembal) [inline core/src/operator.rs:527]: why clone params

File: core/src/operator.rs [hunk 5]
```diff
@@ -655,6 +666,10 @@ where
 
         txs_to_be_sent.push(operator_takes_tx.tx.raw_hex());
 
+        Ok(txs_to_be_sent)
+
+        // TODO: Is this removable?
```
Comment (ekrembal) [inline core/src/operator.rs:671]: yes we can remove

File: core/src/operator.rs [hunk 6]
```diff
@@ -714,14 +728,14 @@ where
         self.set_funding_utxo(funding_utxo).await
     }
 
-    async fn new_withdrawal_sig_rpc(
+    async fn new_signed_withdrawal(
```
Comment (ekrembal) [inline core/src/operator.rs:731]: lets not change the name

File: core/src/traits/rpc.rs [hunk 7]
```diff
@@ -72,7 +72,7 @@ pub trait OperatorRpc {
     /// checks wheter sig is for a correct withdrawal from citrea,
     /// checks the signature, calls is_profitable, if is profitable pays the withdrawal,
     /// adds it to flow, when its finalized, proves on citrea, sends kickoff2
-    async fn new_withdrawal_sig_rpc(
+    async fn new_signed_withdrawal(
```
Comment (ekrembal) [inline core/src/traits/rpc.rs:75]: lets not change the name

File: core/src/transaction_builder.rs [hunk 8]
```diff
@@ -19,37 +20,51 @@ pub struct TxHandler {
...
-        (0..n).fold(TaprootBuilder::new(), |acc, i| {
-            acc.add_leaf(m - ((i >= n - k) as u8), scripts[i].clone())
-                .unwrap()
-        })
-    } else {
-        TaprootBuilder::new()
+) -> (Address, TaprootSpendInfo) {
+    let scripts_len = scripts.len();
+
+    let taproot_builder = match scripts_len.cmp(&1) {
```
Comment (ekrembal) [inline core/src/transaction_builder.rs:55]: let's keep this as is

**Review by ekrembal — CHANGES_REQUESTED** [review]
Overall great pr

File: core/src/operator.rs [hunk 9]
```diff
@@ -598,22 +606,17 @@ where
 
         txs_to_be_sent.push(slash_or_take_tx_handler.tx.raw_hex());
 
-        tracing::debug!(
-            "Found txs to be sent with slash_or_take_tx: {:?}",
-            txs_to_be_sent
-        );
-
-        let move_tx_handler = transaction_builder::create_move_tx(
+        let move_tx_handler = transaction_builder::create_move_tx_handler(
```
Comment (ekrembal) [inline core/src/operator.rs:609]: why not use create_move_tx here

File: core/src/transaction_builder.rs [hunk 10]
```diff
@@ -72,19 +87,38 @@ pub fn create_taproot_address(
...
+///
+/// - [`Address`]: Deposit taproot Bitcoin address
+/// - [`TaprootSpendInfo`]: Deposit address's taproot spending information
+///
+/// # Panics
+///
+/// Panics if given parameters are malformed.
 pub fn generate_deposit_address(
-    nofn_xonly_pk: &XOnlyPublicKey,
+    nofn_xonly_public_key: XOnlyPublicKey,
```
Comment (ekrembal) [inline core/src/transaction_builder.rs:113]: let use nofn_xonly_pk everywhere for consistency

File: core/src/transaction_builder.rs [hunk 11]
```diff
@@ -231,22 +296,21 @@ pub fn create_kickoff_utxo_tx(
...
-    nofn_xonly_pk: &XOnlyPublicKey,
+    nofn_xonly_pk: XOnlyPublicKey,
     network: bitcoin::Network,
     user_takes_after: u32,
     operator_takes_after: u32,
     bridge_amount_sats: u64,
 ) -> TxHandler {
     // First recreate the move_tx and move_txid. We can give dummy values for some of the parameters since we are only interested in txid.
-    let move_tx_handler = create_move_tx(
+    let move_tx_handler = create_move_tx_handler(
```
Comment (ekrembal) [inline core/src/transaction_builder.rs:311]: Why not create_move_tx here

File: core/src/transaction_builder.rs [hunk 12]
```diff
@@ -339,17 +402,17 @@ pub fn create_operator_takes_tx(
...
         script_builder::generate_relative_timelock_script(operator_xonly_pk, operator_takes_after);
     let (slash_or_take_address, slash_or_take_spend_info) = create_taproot_address(
         &[relative_timelock_script.clone()],
-        Some(*nofn_xonly_pk),
+        Some(nofn_xonly_pk),
         network,
     );
 
-    // Sanity check
+    // Sanity check TODO: No asserts outside of tests
```
Comment (ekrembal) [inline core/src/transaction_builder.rs:415]: Change this with an error

File: core/src/verifier.rs [hunk 13]
```diff
@@ -93,28 +93,22 @@ where
...
         let num_required_nonces = 2 * self.operator_xonly_pks.len() + 1;
 
-        let mut dbtx = self.db.begin_transaction().await?;
         // Check if we already have pub_nonces for this deposit_outpoint.
-        let pub_nonces_from_db = self
-            .db
-            .get_pub_nonces(Some(&mut dbtx), deposit_outpoint)
-            .await?;
-        if let Some(pub_nonces) = pub_nonces_from_db {
+        if let Some(pub_nonces) = self.db.get_pub_nonces(None, deposit_outpoint).await? {
```
Comment (ekrembal) [inline core/src/verifier.rs:97]: Let's keep it as is, but can you create an issue @ceyhunsen ?

**Review by ekrembal — CHANGES_REQUESTED** [review]

File: core/src/operator.rs (hunk 9 above)
Comment (ceyhunsen) [reply core/src/operator.rs:609]: 3603f7331a703f8f5aea7770fe63cfae18cdb778

File: core/src/transaction_builder.rs (hunk 11 above)
Comment (ceyhunsen) [reply core/src/transaction_builder.rs:311]: fbb190ff5f05995246feed3479c33a528b0bc7ca

File: core/src/transaction_builder.rs (hunk 10 above)
Comment (ceyhunsen) [reply core/src/transaction_builder.rs:113]: c81b37d2355697129e7c8e7c9694ee4e1e5e6a46

File: core/src/verifier.rs (hunk 13 above)
Comment (ceyhunsen) [reply core/src/verifier.rs:97]: reverted in b90bb81b2f85479271873a7d05af425dfbe925ff
issue: https://github.com/chainwayxyz/clementine/issues/325

**Review by ekrembal — APPROVED** [review]
